name: A job to draw lbr design
on:
  push:
    paths-ignore:
      - 'imgs'

jobs:
  drawing_jobs:
    runs-on: ubuntu-latest
    name: A job to draw lbr design
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: drawing
        uses: botamochi6277/EagleDrawer@main
      - name: git setting
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: |
          git config --local user.email "action_runner@users.noreply.github.com"
          git config --local user.name "action runner"
      - name: Commit and push files
        run: |
          git add .
          git commit -m "Add imgs" -a
          git pull
          git push origin main -u
