name: A job to draw lbr design
on:
  push:
    paths-ignore:
      - 'imgs'

jobs:
  drawing_jobs:
    runs-on: ubuntu-latest
    name: A job to draw lbr design
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: move workdir
        run: cd $GITHUB_WORKSPACE
      - name: drawing
        uses: botamochi6277/EagleDrawer@main
        with:
          filenames: '*.lbr'
